name: Pester Tests
on:
  push:
    branches: [ main ]
jobs:
  Test-DesktopEdition:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Pester tests
      shell: powershell
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Microsoft.PowerShell.SecretManagement -RequiredVersion 1.1.0
        Import-Module Pester -MinimumVersion 5.2
        $cfg = [PesterConfiguration]@{Run=@{Exit=$true}}
        Invoke-Pester -Configuration $cfg
  Test-CoreEdition:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run Pester tests
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Microsoft.PowerShell.SecretManagement -RequiredVersion 1.1.0
        Import-Module Pester -MinimumVersion 5.2
        $cfg = [PesterConfiguration]@{Run=@{Exit=$true}}
        Invoke-Pester -Configuration $cfg
